name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches:
      - master

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  swiftlint:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Run SwiftLint
        uses: norio-nomura/action-swiftlint@9f4dcd7fd46b4e75d7935cf2f4df406d5cae3684 # 3.2.1
        with:
          args: --strict

  swift-format:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Show Swift version
        run: swift --version
      - name: Run swift-format
        run: |
          swift format lint --parallel --recursive --strict Package.swift WSDL2Swift.swift WSDL2Swift/ Tests/

  ci:
    needs: [swiftlint, swift-format]
    permissions:
      contents: read
    runs-on: macos-26
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Show Xcode version
        run: |
          xcodebuild -version

      - name: Cache SwiftPM
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            .build
          key: ${{ runner.os }}-swiftpm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-swiftpm-

      - name: Run build
        run: |
          swift build --triple "$TARGET_TRIPLE" -Xswiftc -sdk -Xswiftc $(xcrun --sdk iphonesimulator --show-sdk-path) -Xcc -isysroot -Xcc $(xcrun --sdk iphonesimulator --show-sdk-path)
        env:
          TARGET_TRIPLE: arm64-apple-ios18.0-simulator

      - name: Generate SOAP client code
        run: |
          swift run WSDL2SwiftCLI --public-memberwise-init --out Tests/WSDL2SwiftTests/WSDL.swift Tests/WSDL2SwiftTests/tempconvert.xml

      - name: Run test
        run: |
          swift test
